version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"

  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
    logging:
      driver: "none"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: "none"

  api:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017
      - C_FORCE_ROOT=1
      - PYTHONUNBUFFERED=1
#    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
